services:
  pgdatabase:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=world_forest
    ports:
      - 5432:5432
    volumes:
      - ./data_postgres:/var/lib/postgresql/data:rw
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=thebad@coder.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin:rw